var config={databaseURL:"https://idekoranggun-default-rtdb.asia-southeast1.firebasedatabase.app/",apiKey:"AIzaSyBGX4qmiowCbcAqGNRA7Aml6ZRBi4lkCwU",authDomain:"idekoranggun.firebaseapp.com",projectId:"idekoranggun",storageBucket:"idekoranggun.appspot.com",messagingSenderId:"788228026301",appId:"1:788228026301:web:370a25ba6a735dad17acd4",measurementId:"G-2EV82EP0CY"};firebase.initializeApp(config);var database=firebase.database(),winnerRef=database.ref("pemenang");function showDataMembers(e){var t="";e.forEach(function(e){t+=`<tr>
                        <td>${e.val().ig}</td>
                    </tr>`}),document.getElementById("tbody").innerHTML=t}function showDataErr(e){console.log(e)}function activateNavigation(){const e=document.querySelectorAll(".section"),t=document.createElement("nav"),a=Array.from(e).map(e=>`
            <div class="nav-item" data-for-section="${e.id}">
                <a href="#${e.id}" class="nav-link"></a>
            </div>
        `);t.classList.add("nav"),t.innerHTML=a.join("");const n=new IntersectionObserver(e=>{document.querySelectorAll(".nav-link").forEach(e=>{e.classList.remove("nav-link-selected")});e=e.filter(e=>e.isIntersecting)[0];document.querySelector(`.nav-item[data-for-section="${e.target.id}"] .nav-link`).classList.add("nav-link-selected")},{threshold:.5});e.forEach(e=>n.observe(e)),document.body.appendChild(t);const i=document.createElement("nav"),r=Array.from(e).map(e=>{return`
        <a href="#${e.id}" class="anis_nav_link" data-for-bottom="${e.id}">
          <i class="material-icons anis_nav_icon">${"spin"===e.id?"emoji_events":"pembukuan"===e.id?"auto_stories":"peserta"===e.id?"people_alt":e.id}</i>
          <span class="anis_nav_text">${e.id.toUpperCase()}</span>
        </a>
        `});i.classList.add("anis_nav"),i.innerHTML=r.join("");const o=new IntersectionObserver(e=>{document.querySelectorAll(".anis_nav_link").forEach(e=>{e.classList.remove("anis_nav_link--active")});e=e.filter(e=>e.isIntersecting)[0];document.querySelector(`.anis_nav_link[data-for-bottom="${e.target.id}"]`).classList.add("anis_nav_link--active")},{threshold:.5});e.forEach(e=>o.observe(e)),document.body.appendChild(i)}function cannon(){confetti({particleCount:100,spread:70,origin:{y:.6}})}function random(){function e(e,t){return Math.random()*(t-e)+e}confetti({angle:e(55,125),spread:e(50,70),particleCount:e(50,100),origin:{y:.6}})}function realistic(){var a={origin:{y:.7}};function e(e,t){confetti(Object.assign({},a,t,{particleCount:Math.floor(200*e)}))}e(.25,{spread:26,startVelocity:55}),e(.2,{spread:60}),e(.35,{spread:100,decay:.91,scalar:.8}),e(.1,{spread:120,startVelocity:25,decay:.92,scalar:1.2}),e(.1,{spread:120,startVelocity:45})}function fireworks(){var t=Date.now()+15e3,a={startVelocity:30,spread:360,ticks:60,zIndex:0};function n(e,t){return Math.random()*(t-e)+e}var i=setInterval(function(){var e=t-Date.now();if(e<=0)return winnerMusic.pause(),clearInterval(i);e=e/15e3*50;confetti(Object.assign({},a,{particleCount:e,origin:{x:n(.1,.3),y:Math.random()-.2}})),confetti(Object.assign({},a,{particleCount:e,origin:{x:n(.7,.9),y:Math.random()-.2}}))},250)}function snow(){var n=Date.now()+15e3,i=1;function r(e,t){return Math.random()*(t-e)+e}!function e(){var t=n-Date.now(),a=Math.max(200,t/15e3*500);i=Math.max(.8,i-.001),confetti({particleCount:1,startVelocity:0,ticks:a,origin:{x:Math.random(),y:Math.random()*i-.2},colors:["#ffffff"],shapes:["circle"],gravity:r(.4,.6),scalar:r(.4,1),drift:r(-.4,.4)}),0<t&&requestAnimationFrame(e)}()}function continuous(){var t=Date.now()+15e3,a=["#bb0000","#ffffff"];!function e(){confetti({particleCount:2,angle:60,spread:55,origin:{x:0},colors:a}),confetti({particleCount:2,angle:120,spread:55,origin:{x:1},colors:a}),Date.now()<t&&requestAnimationFrame(e)}()}winnerRef.on("value",showDataMembers,showDataErr),activateNavigation();var namesList=[],time=0;const winnerMusic=new Audio("/applause.wav"),hororMusic=new Audio("/horor.wav");let i=0,intervalHandle=null,timeOver=null;const startButton=document.getElementById("startButton");function getWinner(e){e.forEach(function(e){namesList.push({ig:e.val().ig,id:e.key})})}function getWinnerErr(e){return[]}winnerRef.on("value",getWinner,showDataErr),startButton.addEventListener("click",function(){hororMusic.play(),startButton.style.display="none",intervalHandle=setInterval(function(){headerNames.textContent=namesList[i++%namesList.length].ig},100*Math.random());let e=11;timeOver=setInterval(()=>{e<=0&&(winnerMusic.play(),hororMusic.pause(),startButton.style.display="",fireworks(),clearInterval(intervalHandle)),0<e?e--:(startButton.style.display="",clearInterval(timeOver))},1e3)});